name = "list-cutter-frontend"
main = "src/worker.js"
compatibility_date = "2024-12-01"

[assets]
directory = "dist"
binding = "ASSETS"

[vars]
ENVIRONMENT = "development"

[env.production.vars]
ENVIRONMENT = "production"

[env.preview.vars]
ENVIRONMENT = "preview"