name = "cutty-frontend"
main = "src/worker.js"
compatibility_date = "2024-12-01"

# Enable Workers logs for debugging and monitoring
logfmt = "json"
send_metrics = true

# Enable versioning and gradual deployments
[version_metadata]
enable_versions = true

# Asset configuration
[assets]
directory = "dist"
binding = "ASSETS"

# Environment variables
[vars]
ENVIRONMENT = "development"

# Production environment - Routes disabled for unified worker migration  
[env.production]
vars = { ENVIRONMENT = "production" }
# routes = [
#   { pattern = "cutty.emilycogsdill.com/*", zone_name = "emilycogsdill.com" }
# ]