name = "list-cutter-frontend"
main = "src/worker.js"
compatibility_date = "2024-12-01"

[assets]
directory = "dist"
binding = "ASSETS"

[vars]
ENVIRONMENT = "development"

# Production environment with custom domain
[env.production]
vars = { ENVIRONMENT = "production" }
routes = [
  { pattern = "list-cutter.emilycogsdill.com/*", zone_name = "emilycogsdill.com" }
]

# Preview environment
[env.preview.vars]
ENVIRONMENT = "preview"