# DEPRECATED: This frontend worker is no longer used
# All frontend serving is now handled by the unified "cutty" worker
# This file is kept for reference only

name = "cutty-frontend-deprecated"
main = "src/worker.js"
compatibility_date = "2024-12-01"

# DISABLED: This worker should not be deployed
workers_dev = false

# Asset configuration (kept for reference)
[assets]
directory = "dist"
binding = "ASSETS"

# Environment variables (kept for reference)
[vars]
ENVIRONMENT = "deprecated"

# All environments disabled - unified worker handles all traffic
# [env.production]
# vars = { ENVIRONMENT = "production" }
# routes = [
#   { pattern = "cutty.emilycogsdill.com/*", zone_name = "emilycogsdill.com" }
# ]