name = "cutty"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

# Enable versioning and gradual deployments
[version_metadata]
enable_versions = true

# Frontend static assets
[assets]
directory = "./public"
binding = "ASSETS"

# Development configuration
[dev]
port = 8788
local_protocol = "http"
ip = "127.0.0.1"

# Build configuration
[build]
command = "npm run build:worker"

# Development environment
[vars]
ENVIRONMENT = "development"
API_VERSION = "v1"
CORS_ORIGIN = "http://localhost:5173"
MAX_FILE_SIZE = "52428800"
JWT_ISSUER = "cutty"
JWT_AUDIENCE = "cutty-api"
LOG_LEVEL = "debug"

# Development bindings
[[d1_databases]]
binding = "DB"
database_name = "cutty-dev"
database_id = "2f87e313-31ff-4298-ab18-552fa5a1ce0e"
migrations_dir = "./migrations"

[[r2_buckets]]
binding = "FILE_STORAGE"
bucket_name = "cutty-files-dev"
preview_bucket_name = "cutty-files-preview"

[[kv_namespaces]]
binding = "AUTH_TOKENS"
id = "061bd8c2dc2e4616b3eaadd17248eb43"
preview_id = "6d9f7f3782074462b90513852cdf20f6"

# Queue bindings (for async processing)
[[queues.producers]]
binding = "CSV_QUEUE"
queue = "csv-processing"

[[queues.consumers]]
queue = "csv-processing"

# Analytics Engine binding
[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "cutty_analytics"

# Rate limiting
[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1"
simple = { limit = 100, period = 60 }

# Staging environment
[env.staging]
name = "cutty-staging"
vars = { 
  ENVIRONMENT = "staging",
  API_VERSION = "v1",
  CORS_ORIGIN = "https://staging.cutty.com",
  MAX_FILE_SIZE = "52428800",
  JWT_ISSUER = "cutty",
  JWT_AUDIENCE = "cutty-api",
  LOG_LEVEL = "info",
  SENTRY_ENVIRONMENT = "staging"
}

# Staging domain for testing
routes = [
  { pattern = "staging.cutty.com/*", zone_name = "cutty.com" }
]

[[env.staging.d1_databases]]
binding = "DB"
database_name = "cutty-staging"
database_id = "e16924c6-be97-4012-88ac-79ff31fd5304"

[[env.staging.r2_buckets]]
binding = "FILE_STORAGE"
bucket_name = "cutty-files-staging"

[[env.staging.kv_namespaces]]
binding = "AUTH_TOKENS"
id = "061bd8c2dc2e4616b3eaadd17248eb43"

# Production environment
[env.production]
name = "cutty-production"
vars = { 
  ENVIRONMENT = "production",
  API_VERSION = "v1",
  CORS_ORIGIN = "https://cutty.com",
  MAX_FILE_SIZE = "52428800",
  JWT_ISSUER = "cutty",
  JWT_AUDIENCE = "cutty-api",
  LOG_LEVEL = "info",
  SENTRY_ENVIRONMENT = "production"
}

# Single domain for entire application
routes = [
  { pattern = "cutty.com/*", zone_name = "cutty.com" },
  { pattern = "www.cutty.com/*", zone_name = "cutty.com" }
]

# Production bindings
[[env.production.d1_databases]]
binding = "DB"
database_name = "cutty-production"
database_id = "0a6c6836-02e8-4f91-a37a-7eb82aa58e0f"

[[env.production.r2_buckets]]
binding = "FILE_STORAGE"
bucket_name = "cutty-files-production"

[[env.production.kv_namespaces]]
binding = "AUTH_TOKENS"
id = "PRODUCTION_KV_ID"

# Rate limiting for production
[[env.production.unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1"
simple = { limit = 100, period = 60 }