name = "cutty"
main = "cloudflare/workers/src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "cutty.emilycogsdill.com/*", zone_name = "emilycogsdill.com" }
]

[vars]
ENVIRONMENT = "development"
API_VERSION = "v1"
CORS_ORIGIN = "https://cutty.emilycogsdill.com"
MAX_FILE_SIZE = "52428800"
JWT_ISSUER = "cutty"
JWT_AUDIENCE = "cutty"

[[d1_databases]]
binding = "DB"
database_name = "cutty-dev"
database_id = "2f87e313-31ff-4298-ab18-552fa5a1ce0e"

[[r2_buckets]]
binding = "FILE_STORAGE"
bucket_name = "cutty-files-dev"
preview_bucket_name = "cutty-files-dev"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "cutty-metrics"