services:
  web:
    container_name: list_cutter_web
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env.new
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
      - "5173:5173"
    depends_on:
      - web-db
    command: ["sh", "-c", "/app/scripts/cmd-web.sh --init-db"]

  web-db:
    image: postgres:15
    container_name: list_cutter_db
    env_file: .env.new
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
