# Wrangler configuration for List Cutter Phase 4 - D1 Database Migration

name = "list-cutter"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.development]
name = "list-cutter-dev"

[env.production]
name = "list-cutter-prod"

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "list-cutter-dev"
database_id = "fc5af020-09f2-4235-8a47-590140e8ad74"
preview_database_id = "fc5af020-09f2-4235-8a47-590140e8ad74"

# Environment variables
[vars]
ENVIRONMENT = "development"
DEBUG = "true"

# Development settings
[env.development.vars]
ENVIRONMENT = "development"
DEBUG = "true"

# Production settings
[env.production.vars]
ENVIRONMENT = "production"
DEBUG = "false"

# KV namespaces (for future use)
# [[kv_namespaces]]
# binding = "LIST_CUTTER_CACHE"
# id = "placeholder-for-kv-id"
# preview_id = "placeholder-for-preview-kv-id"

# R2 buckets (for future phases)
# [[r2_buckets]]
# binding = "LIST_CUTTER_FILES"
# bucket_name = "list-cutter-files"
# preview_bucket_name = "list-cutter-files-preview"

# Build configuration
[build]
command = "npm run build"
cwd = "src"

# Durable Objects (for future use)
# [[durable_objects.bindings]]
# name = "LIST_CUTTER_DO"
# class_name = "ListCutterDurableObject"
# script_name = "list-cutter"