# GitHub CLI Configuration
# Project-specific GitHub management commands and label standards

GitHubLabels: &GitHubLabels
  standard_labels:
    # Issue types
    bug:
      color: "d73a4a"
      description: "Something isn't working"
    enhancement:
      color: "a2eeef"
      description: "New feature or request"
    documentation:
      color: "0075ca"
      description: "Improvements or additions to documentation"
    
    # Priority levels
    "priority:high":
      color: "b60205"
      description: "High priority item"
    "priority:medium":
      color: "fbca04"
      description: "Medium priority item"
    "priority:low":
      color: "0e8a16"
      description: "Low priority item"
    
    # Project-specific
    wrangler:
      color: "7057ff"
      description: "Cloudflare Wrangler related"
    deployment:
      color: "1d76db"
      description: "Deployment related"
    migration:
      color: "5319e7"
      description: "Django to Workers migration"
    security:
      color: "ee0701"
      description: "Security related issue"
    performance:
      color: "0052cc"
      description: "Performance optimization"

GitHubCommands: &GitHubCommands
  label_creation:
    create_all_standard_labels: |
      gh label create "bug" --color "d73a4a" --description "Something isn't working" || true
      gh label create "enhancement" --color "a2eeef" --description "New feature or request" || true
      gh label create "documentation" --color "0075ca" --description "Improvements or additions to documentation" || true
      gh label create "priority:high" --color "b60205" --description "High priority item" || true
      gh label create "priority:medium" --color "fbca04" --description "Medium priority item" || true
      gh label create "priority:low" --color "0e8a16" --description "Low priority item" || true
      gh label create "wrangler" --color "7057ff" --description "Cloudflare Wrangler related" || true
      gh label create "deployment" --color "1d76db" --description "Deployment related" || true
      gh label create "migration" --color "5319e7" --description "Django to Workers migration" || true
      gh label create "security" --color "ee0701" --description "Security related issue" || true
      gh label create "performance" --color "0052cc" --description "Performance optimization" || true

  issue_creation_with_fallback: |
    # Function to create issue with automatic label creation fallback
    create_issue_with_labels() {
      local title="$1"
      local body="$2"
      local labels="$3"
      local assignee="$4"
      
      # Attempt to create issue
      if [ -n "$assignee" ]; then
        gh issue create --title "$title" --body "$body" --label "$labels" --assignee "$assignee" || {
          echo "Creating missing labels for: $labels"
          # Parse labels and create each one
          IFS=',' read -ra LABEL_ARRAY <<< "$labels"
          for label in "${LABEL_ARRAY[@]}"; do
            case "$label" in
              "bug") gh label create "bug" --color "d73a4a" --description "Something isn't working" || true ;;
              "enhancement") gh label create "enhancement" --color "a2eeef" --description "New feature or request" || true ;;
              "priority:high") gh label create "priority:high" --color "b60205" --description "High priority item" || true ;;
              "priority:medium") gh label create "priority:medium" --color "fbca04" --description "Medium priority item" || true ;;
              "priority:low") gh label create "priority:low" --color "0e8a16" --description "Low priority item" || true ;;
              "wrangler") gh label create "wrangler" --color "7057ff" --description "Cloudflare Wrangler related" || true ;;
              "deployment") gh label create "deployment" --color "1d76db" --description "Deployment related" || true ;;
              "migration") gh label create "migration" --color "5319e7" --description "Django to Workers migration" || true ;;
              "security") gh label create "security" --color "ee0701" --description "Security related issue" || true ;;
              "performance") gh label create "performance" --color "0052cc" --description "Performance optimization" || true ;;
              *) gh label create "$label" --color "cccccc" --description "Custom label" || true ;;
            esac
          done
          # Retry issue creation
          gh issue create --title "$title" --body "$body" --label "$labels" --assignee "$assignee"
        }
      else
        gh issue create --title "$title" --body "$body" --label "$labels" || {
          echo "Creating missing labels for: $labels"
          # Same label creation logic as above
          IFS=',' read -ra LABEL_ARRAY <<< "$labels"
          for label in "${LABEL_ARRAY[@]}"; do
            case "$label" in
              "bug") gh label create "bug" --color "d73a4a" --description "Something isn't working" || true ;;
              "enhancement") gh label create "enhancement" --color "a2eeef" --description "New feature or request" || true ;;
              "priority:high") gh label create "priority:high" --color "b60205" --description "High priority item" || true ;;
              "priority:medium") gh label create "priority:medium" --color "fbca04" --description "Medium priority item" || true ;;
              "priority:low") gh label create "priority:low" --color "0e8a16" --description "Low priority item" || true ;;
              "wrangler") gh label create "wrangler" --color "7057ff" --description "Cloudflare Wrangler related" || true ;;
              "deployment") gh label create "deployment" --color "1d76db" --description "Deployment related" || true ;;
              "migration") gh label create "migration" --color "5319e7" --description "Django to Workers migration" || true ;;
              "security") gh label create "security" --color "ee0701" --description "Security related issue" || true ;;
              "performance") gh label create "performance" --color "0052cc" --description "Performance optimization" || true ;;
              *) gh label create "$label" --color "cccccc" --description "Custom label" || true ;;
            esac
          done
          # Retry issue creation
          gh issue create --title "$title" --body "$body" --label "$labels"
        }
      fi
    }

LabelPatterns: &LabelPatterns
  common_combinations:
    - "bug,priority:high"
    - "enhancement,priority:medium"
    - "deployment,wrangler"
    - "migration,enhancement"
    - "security,priority:high"
    - "performance,enhancement"
    - "bug,wrangler,priority:high"
    - "documentation,enhancement,priority:low"