// Generated by Wrangler by running `wrangler types`

interface Env {
	AUTH_TOKENS: KVNamespace;
	ENVIRONMENT: "development" | "staging" | "production";
	API_VERSION: "v1";
	CORS_ORIGIN: "http://localhost:5173" | "https://staging.cutty.com" | "https://cutty.com";
	MAX_FILE_SIZE: "52428800";
	JWT_ISSUER: "cutty";
	JWT_AUDIENCE: "cutty-api";
	JWT_SECRET: string;
	JWT_REFRESH_SECRET: string;
	DB_ENCRYPTION_KEY: string;
	DEBUG_MODE: string;
	LOG_LEVEL: string;
	FILE_STORAGE: R2Bucket;
	DB: D1Database;
	ANALYTICS: AnalyticsEngineDataset;
	RATE_LIMITER: RateLimit;
	CSV_QUEUE: Queue;
}
