name = "cutty-api"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

# R2 Storage bindings
[[r2_buckets]]
binding = "FILE_STORAGE"
bucket_name = "cutty-files-dev"

# Environment variables
[vars]
ENVIRONMENT = "development"
MAX_FILE_SIZE = "52428800"