name = "cutty-dev"

# 🚨🚨🚨 CRITICAL ENVIRONMENT CONFIGURATION 🚨🚨🚨
# ⚠️  DEVELOPMENT: worker cutty-dev → database cutty-dev → route cutty-dev.emilycogsdill.com
# ⚠️  PRODUCTION: worker cutty → database cutty-prod → route cutty.emilycogsdill.com
# ⚠️  NO STAGING ENVIRONMENT EXISTS
# 🚨🚨🚨 NEVER CHANGE THIS CONFIGURATION 🚨🚨🚨

routes = [
  { pattern = "cutty-dev.emilycogsdill.com/*", zone_name = "emilycogsdill.com" }
]
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

# Upload optimization
upload_source_maps = false
minify = true

# Asset configuration for serving frontend
[assets]
directory = "../../app/frontend/dist"
binding = "ASSETS"

# Enable Wrangler logs (v3.88.0+)
[observability.logs]
enabled = true

# Enable versioning and gradual deployments
# [version_metadata]
# enable_versions = true

# Development configuration
[dev]
port = 8788
local_protocol = "http"
ip = "127.0.0.1"

# Build configuration - optimized for faster deployment
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

# Environment variables (non-sensitive)
[vars]
ENVIRONMENT = "development"
API_VERSION = "v1"
CORS_ORIGIN = "https://cutty-dev.emilycogsdill.com"
FRONTEND_URL = "https://cutty-dev.emilycogsdill.com"
MAX_FILE_SIZE = "52428800" # 50MB in bytes
JWT_ISSUER = "cutty"
JWT_AUDIENCE = "cutty"
SECURITY_PERFORMANCE_THRESHOLD = "100"
SECURITY_METRICS_RETENTION_DAYS = "30"
SECURITY_ENABLE_REAL_TIME_MONITORING = "true"
AI_WORKER_URL = "https://ai.emilycogsdill.com"
AGENT_ENABLED = "true"
AGENT_URL = "https://cutty-agent.emilycogsdill.com"
# ✅ SECRETS CONFIGURED: All required secrets are set via Cloudflare Dashboard
# ✅ JWT_SECRET - Authentication tokens (CONFIGURED)
# ✅ API_KEY_SALT - API key generation (CONFIGURED)  
# ✅ GOOGLE_CLIENT_ID - OAuth client ID (CONFIGURED)
# ✅ GOOGLE_CLIENT_SECRET - OAuth client secret (CONFIGURED)
# ✅ GOOGLE_REDIRECT_URI - OAuth callback URL (CONFIGURED)
# These secrets are automatically available to the worker at runtime

# D1 Database bindings
[[d1_databases]]
binding = "DB"
database_name = "cutty-dev"
database_id = "624214be-77a6-4501-b4c7-69b394084081"
preview_database_id = "624214be-77a6-4501-b4c7-69b394084081"  # Same as database_id for remote development
migrations_dir = "./migrations"
migrations_table = "d1_migrations"

# Backup D1 Database (Cross-region) - TODO: Create actual backup database
# [[d1_databases]]
# binding = "BACKUP_DATABASE"
# database_name = "cutty-backup-dev"
# database_id = "backup-db-id-placeholder"

# R2 Storage bindings
[[r2_buckets]]
binding = "FILE_STORAGE"
bucket_name = "cutty-files-dev"
preview_bucket_name = "cutty-files-dev"

# Backup R2 Storage (Cross-region) - TODO: Create actual backup bucket
# [[r2_buckets]]
# binding = "BACKUP_STORAGE"
# bucket_name = "cutty-backup-dev"
# preview_bucket_name = "cutty-backup-dev"

# Security KV Namespaces (Development)
[[kv_namespaces]]
binding = "CUTTY_SECURITY_CONFIG"
id = "a6973edd26304221934017997dbd147e"
preview_id = "a6973edd26304221934017997dbd147e"

[[kv_namespaces]]
binding = "CUTTY_SECURITY_EVENTS"
id = "e696502dea8942a8acb47e2ac474e248"
preview_id = "e696502dea8942a8acb47e2ac474e248"

[[kv_namespaces]]
binding = "CUTTY_SECURITY_METRICS"
id = "805adc47af9c4e8aa7ddf5b412ea3083"
preview_id = "805adc47af9c4e8aa7ddf5b412ea3083"

[[kv_namespaces]]
binding = "CUTTY_QUOTA_TRACKING"
id = "4c1a53aaab2846a3b11ee39416e6b1dd"
preview_id = "4c1a53aaab2846a3b11ee39416e6b1dd"

# Backup Configuration KV Namespace - TODO: Create actual KV namespace
# [[kv_namespaces]]
# binding = "BACKUP_CONFIG"
# id = "backup-config-kv-id-placeholder"
# preview_id = "backup-config-kv-id-placeholder"

# Performance Optimization Cache KV Namespace - Issue #69 - TODO: Create actual KV namespace
# [[kv_namespaces]]
# binding = "CACHE_KV"
# id = "performance-cache-kv-id-placeholder"
# preview_id = "performance-cache-kv-id-placeholder"

# Phase 8 Deployment KV Namespace - For blue-green deployment state management
# TODO: Create actual KV namespace for deployment management
# [[kv_namespaces]]
# binding = "DEPLOYMENT_KV"
# id = "deployment-state-kv-id-placeholder"
# preview_id = "deployment-state-kv-id-placeholder"

# AUTH_KV namespace for JWT token storage and blacklisting
[[kv_namespaces]]
binding = "AUTH_KV"
id = "c490355daf9b4b84b484303d08c42eb2"
preview_id = "c490355daf9b4b84b484303d08c42eb2"

# TEMP_FILE_KEYS namespace for handling R2 eventual consistency
# This namespace is REQUIRED for synthetic data downloads to work properly
[[kv_namespaces]]
binding = "TEMP_FILE_KEYS"
id = "607ebf3e08bb4d1abe4252aa2b968e38"
preview_id = "607ebf3e08bb4d1abe4252aa2b968e38"

# Analytics Engine binding - Required for monitoring
[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "cutty-metrics"

# Durable Objects for AI Agent
# [[durable_objects]]
# binding = "CUTTY_AGENT"
# class_name = "CuttyAgent"
# script_name = "cutty-dev"
# Commented out - using external agent via WebSocket proxy

# Cron triggers disabled - segment processing removed
# [triggers]
# crons = ["* * * * *"]  # Every minute for real-time segmentation

# ⚠️  NO STAGING ENVIRONMENT - Only development (cutty-dev) and production (cutty-prod)

# Production environment - separate worker configuration
# Production uses wrangler.prod.toml with worker name "cutty"
# Deploy production with: wrangler deploy --config wrangler.prod.toml

# Service bindings will be configured when needed
# Future service configuration will go here

# Rate limiting rules (commented out - need to configure proper rate limiting)
# Future rate limiting configuration will go here when needed
