name = "cutty-api"
routes = [
  { pattern = "cutty-api.emilycogsdill.com/*", zone_name = "emilycogsdill.com" }
]
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

# Enable Workers logs for debugging and monitoring
logfmt = "json"
send_metrics = true

# Enable versioning and gradual deployments
# [version_metadata]
# enable_versions = true

# Development configuration
[dev]
port = 8788
local_protocol = "http"
ip = "127.0.0.1"

# Build configuration - using wrangler's built-in TypeScript compilation

# Environment variables (non-sensitive)
[vars]
ENVIRONMENT = "development"
API_VERSION = "v1"
CORS_ORIGIN = "https://cutty.emilycogsdill.com"
MAX_FILE_SIZE = "52428800" # 50MB in bytes
JWT_ISSUER = "cutty"
JWT_AUDIENCE = "cutty-api"
SECURITY_PERFORMANCE_THRESHOLD = "100"
SECURITY_METRICS_RETENTION_DAYS = "30"
SECURITY_ENABLE_REAL_TIME_MONITORING = "true"

# D1 Database bindings
[[d1_databases]]
binding = "DB"
database_name = "cutty-dev"
database_id = "2f87e313-31ff-4298-ab18-552fa5a1ce0e"
migrations_dir = "./migrations"

# Backup D1 Database (Cross-region) - TODO: Create actual backup database
# [[d1_databases]]
# binding = "BACKUP_DATABASE"
# database_name = "cutty-backup-dev"
# database_id = "backup-db-id-placeholder"

# R2 Storage bindings
[[r2_buckets]]
binding = "FILE_STORAGE"
bucket_name = "cutty-files-dev"
preview_bucket_name = "cutty-files-dev"

# Backup R2 Storage (Cross-region) - TODO: Create actual backup bucket
# [[r2_buckets]]
# binding = "BACKUP_STORAGE"
# bucket_name = "cutty-backup-dev"
# preview_bucket_name = "cutty-backup-dev"

# Security KV Namespaces (Development)
[[kv_namespaces]]
binding = "CUTTY_SECURITY_CONFIG"
id = "a6973edd26304221934017997dbd147e"
preview_id = "a6973edd26304221934017997dbd147e"

[[kv_namespaces]]
binding = "CUTTY_SECURITY_EVENTS"
id = "e696502dea8942a8acb47e2ac474e248"
preview_id = "e696502dea8942a8acb47e2ac474e248"

[[kv_namespaces]]
binding = "CUTTY_SECURITY_METRICS"
id = "805adc47af9c4e8aa7ddf5b412ea3083"
preview_id = "805adc47af9c4e8aa7ddf5b412ea3083"

[[kv_namespaces]]
binding = "CUTTY_QUOTA_TRACKING"
id = "4c1a53aaab2846a3b11ee39416e6b1dd"
preview_id = "4c1a53aaab2846a3b11ee39416e6b1dd"

# Backup Configuration KV Namespace - TODO: Create actual KV namespace
# [[kv_namespaces]]
# binding = "BACKUP_CONFIG"
# id = "backup-config-kv-id-placeholder"
# preview_id = "backup-config-kv-id-placeholder"

# Performance Optimization Cache KV Namespace - Issue #69 - TODO: Create actual KV namespace
# [[kv_namespaces]]
# binding = "CACHE_KV"
# id = "performance-cache-kv-id-placeholder"
# preview_id = "performance-cache-kv-id-placeholder"

# AUTH_TOKENS KV namespace (commented out - create namespace first)
# [[kv_namespaces]]
# binding = "AUTH_TOKENS"
# id = "your-auth-tokens-kv-namespace-id-here"
# preview_id = "your-auth-tokens-kv-namespace-id-here"

# Analytics Engine binding - Required for monitoring
[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "cutty-metrics"

# Cron triggers for storage metrics aggregation and monitoring
# Collect metrics every 5 minutes
[[triggers.crons]]
cron = "*/5 * * * *"
endpoint = "/api/monitoring/collect-metrics"

# Calculate costs every 6 hours
[[triggers.crons]]
cron = "0 */6 * * *"
endpoint = "/api/monitoring/calculate-costs"

# Generate daily reports at 2 AM UTC
[[triggers.crons]]
cron = "0 2 * * *"
endpoint = "/api/monitoring/generate-daily-report"

# Generate monthly reports on 1st of month at 4 AM UTC
[[triggers.crons]]
cron = "0 4 1 * *"
endpoint = "/api/monitoring/generate-monthly-report"

# Check alerts every minute
[[triggers.crons]]
cron = "*/1 * * * *"
endpoint = "/api/monitoring/check-alerts"

# Cleanup old metrics every Sunday at 5 AM UTC
[[triggers.crons]]
cron = "0 5 * * 0"
endpoint = "/api/monitoring/cleanup-old-metrics"

# Alert system cron triggers
# Alert evaluation every 5 minutes
[[triggers.crons]]
cron = "*/5 * * * *"
endpoint = "/api/alerts/jobs/evaluate"

# Retry failed notifications every 15 minutes
[[triggers.crons]]
cron = "*/15 * * * *"
endpoint = "/api/alerts/jobs/retry-notifications"

# Alert cleanup daily at 3 AM UTC
[[triggers.crons]]
cron = "0 3 * * *"
endpoint = "/api/alerts/jobs/cleanup"

# Alert health check every 10 minutes
[[triggers.crons]]
cron = "*/10 * * * *"
endpoint = "/api/alerts/jobs/health-check"

# Backup system cron triggers
# Daily backup at 2 AM UTC
[[triggers.crons]]
cron = "0 2 * * *"
endpoint = "/api/backup/daily"

# Weekly backup on Sunday at 3 AM UTC
[[triggers.crons]]
cron = "0 3 * * 0"
endpoint = "/api/backup/weekly"

# Monthly backup on 1st at 4 AM UTC
[[triggers.crons]]
cron = "0 4 1 * *"
endpoint = "/api/backup/monthly"

# Auto recovery check every 5 minutes
[[triggers.crons]]
cron = "*/5 * * * *"
endpoint = "/api/disaster-recovery/auto-recovery-check"

# Export cleanup daily at 6 AM UTC
[[triggers.crons]]
cron = "0 6 * * *"
endpoint = "/api/data-export/scheduled-cleanup"

# Staging environment
[env.staging]
name = "cutty-api-staging"
vars = { ENVIRONMENT = "staging", CORS_ORIGIN = "https://staging.cutty.emilycogsdill.com" }
routes = [
  { pattern = "cutty-api-staging.emilycogsdill.com/*", zone_name = "emilycogsdill.com" }
]

# Queue bindings for CSV processing (commented out - create queue first)
# [[queues.producers]]
# binding = "CSV_QUEUE"
# queue = "csv-processing"

# Analytics Engine binding for metrics collection (commented out for debugging)
# [[analytics_engine_datasets]]
# binding = "ANALYTICS"
# dataset = "cutty_analytics"

[[env.staging.r2_buckets]]
binding = "FILE_STORAGE"
bucket_name = "cutty-files-staging"
preview_bucket_name = "cutty-files-preview"

[[env.staging.analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "cutty-metrics-staging"

# KV configuration for staging will be added when needed

# Production environment
[env.production]
name = "cutty-api-production"
vars = { ENVIRONMENT = "production", CORS_ORIGIN = "https://cutty.emilycogsdill.com" }
routes = [
  { pattern = "cutty-api.emilycogsdill.com/*", zone_name = "emilycogsdill.com" }
]

[[env.production.d1_databases]]
binding = "DB"
database_name = "cutty-production"
database_id = "0a6c6836-02e8-4f91-a37a-7eb82aa58e0f"

[[env.production.r2_buckets]]
binding = "FILE_STORAGE"
bucket_name = "cutty-files-prod"
preview_bucket_name = "cutty-files-dev"

[[env.production.analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "cutty-metrics-production"

# KV configuration for production will be added when needed

# Service bindings will be configured when needed
# Future service configuration will go here

# Rate limiting rules (commented out - need to configure proper rate limiting)
# Future rate limiting configuration will go here when needed
