name = "cutty-workers"
main = "dist/index.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[env.development]
name = "cutty-workers-dev"

[env.staging]
name = "cutty-workers-staging"

[[env.staging.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "cutty-files-staging"
preview_bucket_name = "cutty-files-preview"

[env.production]
name = "cutty-workers-prod"

[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "cutty-files-prod"
preview_bucket_name = "cutty-files-preview"

# KV for session/token management
[[kv_namespaces]]
binding = "AUTH_KV"
preview_id = "your-preview-kv-namespace-id"
id = "your-kv-namespace-id"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "cutty-files-dev"
preview_bucket_name = "cutty-files-preview"

[[r2_buckets]]
binding = "R2_BACKUP_BUCKET"
bucket_name = "cutty-backups-dev"
preview_bucket_name = "cutty-backups-preview"

[[env.staging.r2_buckets]]
binding = "R2_BACKUP_BUCKET"
bucket_name = "cutty-backups-staging"
preview_bucket_name = "cutty-backups-preview"

[[env.production.r2_buckets]]
binding = "R2_BACKUP_BUCKET"
bucket_name = "cutty-backups-prod"
preview_bucket_name = "cutty-backups-preview"

binding = "DB"
database_name = "cutty-dev"
database_id = "2f87e313-31ff-4298-ab18-552fa5a1ce0e"
migrations_dir = "./migrations"

# Rate limiting (beta feature)
[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 60, period = 60 }  # 60 requests per minute

[vars]
JWT_SECRET = "your-jwt-secret-here"
MAX_FILE_SIZE = "10485760"
ENVIRONMENT = "development"

# Backup Configuration
BACKUP_RETENTION_DAYS = "30"
BACKUP_SCHEDULE = "daily"
BACKUP_INCREMENTAL_ENABLED = "true"
BACKUP_COMPRESSION_ENABLED = "false"
BACKUP_ENCRYPTION_ENABLED = "false"

# Scheduled backup trigger - runs daily at 2 AM UTC
[triggers]
crons = ["0 2 * * *"]