# Generated by Django 5.1.5 on 2025-02-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list_cutter", "0002_uploadedfile_delete_dummymodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="DummyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
