# Generated by Django 5.1.5 on 2025-02-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("list_cutter", "0003_dummymodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DummyModel",
        ),
    ]
