name: Build and Publish Image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag for the Docker images (e.g. v1.0.0)'
        required: true
        default: 'latest'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: emilycogsdill
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Create .env file for frontend build
        run: |
          printf '%b' "${{ secrets.PROD_ENV }}" > .env

      - name: Build and push frontend image
        uses: docker/build-push-action@v3
        with:
          context: .
          target: frontend-prod
          push: true
          platforms: linux/amd64,linux/arm64
          tags: emilycogsdill/list-cutter-frontend:${{ github.event.inputs.image_tag }}

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: .
          target: backend-prod
          push: true
          platforms: linux/amd64,linux/arm64
          tags: emilycogsdill/list-cutter-backend:${{ github.event.inputs.image_tag }}
