name: Build and Publish Image

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  publish:
    # Run the job if manually triggered OR if the pull request has a label that contains "docker-deploy"
    if: >
      github.event_name == 'workflow_dispatch'
      || (github.event_name == 'pull_request' &&
         contains(join(github.event.pull_request.labels.*.name, ','), 'docker-deploy'))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: emilycogsdill
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: emilycogsdill/list-cutter-backend
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: .
          # Build only the prod-backend stage from your Dockerfile
          target: prod-backend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
