name: Build and Publish Image

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: emilycogsdill
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Generate Docker metadata for backend
        id: meta-backend
        uses: docker/metadata-action@v4
        with:
          images: emilycogsdill/list-cutter-backend
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Generate Docker metadata for frontend
        id: meta-frontend
        uses: docker/metadata-action@v4
        with:
          images: emilycogsdill/list-cutter-frontend
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      #- name: Build and push backend image
      #  uses: docker/build-push-action@v3
      #  with:
      #    context: .
      #    target: prod-backend
      #    push: true
      #    platforms: linux/amd64,linux/arm64
      #    tags: ${{ steps.meta-backend.outputs.tags }}
      #    labels: ${{ steps.meta-backend.outputs.labels }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v3
        with:
          context: .
          target: frontend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}
