name: Cloudflare Workers CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'cloudflare/workers/**'
      - '.github/workflows/cloudflare-workers-ci.yml'

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./cloudflare/workers

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Disable npm cache to avoid version conflicts
          # cache: 'npm'
          # cache-dependency-path: './cloudflare/workers/package-lock.json'

      - name: Clear npm cache and install dependencies
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install

      - name: Build project
        run: npm run build

      - name: Run basic tests
        run: npm test