name: Cloudflare Workers CI

on:
  push:
    branches: [main, feature-cut-mvp]
  pull_request:
    branches: [ main ]
    paths:
      - 'cloudflare/workers/**'
      - '.github/workflows/cloudflare-workers-ci.yml'

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        working-directory: cloudflare/workers
        run: npm ci

      - name: Build project
        working-directory: cloudflare/workers
        run: npm run build

      - name: Run tests
        working-directory: cloudflare/workers
        run: npm test

  e2e-tests:
    name: Playwright E2E Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        working-directory: cloudflare/workers
        run: npm ci
      
      - name: Install Playwright browsers
        working-directory: cloudflare/workers
        run: npx playwright install --with-deps
      
      - name: Run E2E tests
        working-directory: cloudflare/workers
        run: npm run test:e2e
        env:
          CI: true
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
          BASE_URL: https://cutty-dev.emilycogsdill.com
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: |
            cloudflare/workers/e2e/reports/
            cloudflare/workers/e2e/artifacts/
          retention-days: 30
          if-no-files-found: ignore

  deploy-dev:
    name: Deploy to Development
    needs: [test, e2e-tests]
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'deploy-dev')
    
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies - Frontend
        working-directory: app/frontend
        run: npm ci
      
      - name: Build Frontend
        working-directory: app/frontend
        run: npm run build
        env:
          CI: true
          NODE_ENV: production
          VITE_AI_WORKER_API_KEY: ${{ secrets.AI_WORKER_API_KEY }}
      
      - name: Install dependencies - Cloudflare Worker
        working-directory: cloudflare/workers
        run: npm ci

      - name: Deploy to Cloudflare Workers (Development)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: cloudflare/workers
          command: deploy

