name: Build, Test & Deploy

on:
  pull_request:
    branches: [main]
    paths:
      - 'cloudflare/workers/**'
      - 'app/frontend/**'
      - '.github/workflows/cloudflare-workers-ci.yml'
  push:
    branches: [main]
    paths:
      - 'cloudflare/workers/**'
      - 'app/frontend/**'
      - '.github/workflows/cloudflare-workers-ci.yml'

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Build Frontend
      - name: Install dependencies - Frontend
        working-directory: app/frontend
        run: npm ci
      
      - name: Build Frontend
        working-directory: app/frontend
        run: npm run build
        env:
          CI: true
          NODE_ENV: production
          VITE_AI_WORKER_API_KEY: ${{ secrets.AI_WORKER_API_KEY }}

      # Build & Test Cloudflare Workers
      - name: Install dependencies - Workers
        working-directory: cloudflare/workers
        run: npm ci

      - name: Build Workers
        working-directory: cloudflare/workers
        run: npm run build

      - name: Run unit tests
        working-directory: cloudflare/workers
        run: npm test

      # E2E Tests
      - name: Install Playwright browsers
        working-directory: cloudflare/workers
        run: npx playwright install --with-deps
      
      - name: Run E2E tests
        working-directory: cloudflare/workers
        run: npm run test:e2e
        env:
          CI: true
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
          BASE_URL: https://cutty-dev.emilycogsdill.com
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: |
            cloudflare/workers/e2e/reports/
            cloudflare/workers/e2e/artifacts/
          retention-days: 30
          if-no-files-found: ignore


