name: Deploy web application

description: |
  Once you are ready to redeploy the web application, you can trigger this workflow.
  It will pull the latest images from Docker Hub and deploy them to the target host.  
  Just select the image tag you want to deploy (probably `latest` or `dev` unless you are doing something showoffy)
  and the instance you want to deploy to (dev, prod-blue, prod-green).
  **CUTE EVENTUAL TODO (LATER, I AM BUSY): Automate full prod deployment by deploying to prod-blue, waiting to make sure it's working,
  and then deploying to prod-green.

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag for deployment'
        required: true
        default: 'latest'
        options:
          - latest
          - dev
      instance:
        description: 'Instance (dev, prod-blue, prod-green)'
        required: true
        default: 'dev'
        options:
          - dev
          - prod-blue
          - prod-green
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'dev'

jobs:
  deploy-rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up environment variables (from workflow inputs)
        id: set_hosts
        run: |
          if [ "${{ github.event.inputs.instance }}" == "dev" ]; then
            echo "TARGET_HOST=${{ secrets.DEV_HOST }}" >> $GITHUB_ENV
            echo "ENV=${{ secrets.DEV_ENV }}" >> $GITHUB_ENV
          else
            echo "ENV=${{ secrets.PROD_ENV }}" >> $GITHUB_ENV
            if [ "${{ github.event.inputs.instance }}" == "prod-blue" ]; then
              echo "TARGET_HOST=${{ secrets.PROD_BLUE_HOST }}" >> $GITHUB_ENV
            elif [ "${{ github.event.inputs.instance }}" == "prod-green" ]; then
              echo "TARGET_HOST=${{ secrets.PROD_GREEN_HOST }}" >> $GITHUB_ENV
            fi
          fi          

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Create SSH config
        run: |
          cat <<EOF >> ~/.ssh/config
          Host bastion
            HostName "${{ secrets.BASTION_HOST }}"
            User ec2-user
            IdentityFile ~/.ssh/id_rsa

          Host target
            HostName "${{ env.TARGET_HOST }}"
            User ec2-user
            IdentityFile ~/.ssh/id_rsa
            ProxyJump bastion
          EOF

      - name: Preload known hosts for bastion
        run: |
          ssh-keyscan -H "${{ secrets.BASTION_HOST }}" >> ~/.ssh/known_hosts

      - name: Preload target host key via bastion
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.BASTION_HOST }} "ssh-keyscan -H '${{ secrets.DEV_HOST }}'" >> ~/.ssh/known_hosts

      - name: Update .env file on target host # Prod-blue and prod-green use the same .env file
        run: |
          ssh target "printf '%b' \"${{ env.ENV }}\" > list-cutter/.env"

      - name: SSH into target host and pull changes from branch where this workflow was triggered
        run: |
          ssh target "eval \"\$(ssh-agent -s)\" \
          && ssh-add github \
          && cd list-cutter \
          && git fetch origin \
          && git reset --hard origin/${{ github.event.inputs.branch }}"

      - name: SSH into target host and run deployment script
        run: |
          ssh target "cd list-cutter && bash ./scripts/deploy.sh image_tag=${{ github.event.inputs.image_tag }}"