name: Deploy to cutty-dev on Label

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  deploy-dev:
    if: |
      (github.event.action == 'labeled' && github.event.label.name == 'deploy-dev') ||
      (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'deploy-dev'))
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies - Frontend
        working-directory: app/frontend
        run: npm ci
      
      - name: Build Frontend
        working-directory: app/frontend
        run: npm run build
        env:
          CI: true
          NODE_ENV: production
      
      - name: Install dependencies - Cloudflare Worker
        working-directory: cloudflare/workers
        run: npm ci
      
      - name: Run tests
        working-directory: cloudflare/workers
        run: npm test || echo "Tests failed but continuing with deployment to dev"
        continue-on-error: true
      
      - name: Create GitHub deployment
        id: deployment
        uses: actions/github-script@v7
        with:
          script: |
            const deployment = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha,
              environment: 'cutty-dev',
              description: `Deploy PR #${context.payload.pull_request.number} to cutty-dev`,
              auto_merge: false,
              required_contexts: []
            });
            return deployment.data.id;
          result-encoding: string
      
      - name: Deploy to Cloudflare Workers (cutty-dev)
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: cloudflare/workers
          command: deploy --env dev
          wranglerVersion: '3.57.1'
      
      - name: Update deployment status - Success
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: ${{ steps.deployment.outputs.result }},
              state: 'success',
              environment_url: 'https://cutty-dev.emilycogsdill.com',
              description: 'Deployment to cutty-dev succeeded'
            });
      
      - name: Update deployment status - Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: ${{ steps.deployment.outputs.result }},
              state: 'failure',
              description: 'Deployment to cutty-dev failed'
            });
      
      - name: Comment on PR - Success
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `✅ **Deployment to cutty-dev successful!**
            
            🌐 **Environment URL**: https://cutty-dev.emilycogsdill.com
            📝 **Commit**: \`${context.payload.pull_request.head.sha.substring(0, 7)}\`
            🏷️ **Triggered by**: \`deploy-dev\` label
            
            The changes in this PR are now live on the development environment.`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: comment
            });
      
      - name: Comment on PR - Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `❌ **Deployment to cutty-dev failed**
            
            📝 **Commit**: \`${context.payload.pull_request.head.sha.substring(0, 7)}\`
            🏷️ **Triggered by**: \`deploy-dev\` label
            
            Please check the [workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details.`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: comment
            });