name: Deploy to Production on Label

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  deploy-prod:
    if: |
      (github.event.action == 'labeled' && github.event.label.name == 'deploy-prod') ||
      (github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'deploy-prod'))
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies - Frontend
        working-directory: app/frontend
        run: npm ci
      
      - name: Build Frontend
        working-directory: app/frontend
        run: npm run build
        env:
          CI: true
          NODE_ENV: production
      
      - name: Install dependencies - Cloudflare Worker
        working-directory: cloudflare/workers
        run: npm ci
      
      - name: Run tests
        working-directory: cloudflare/workers
        run: npm test
      
      - name: Create GitHub deployment
        id: deployment
        uses: actions/github-script@v7
        with:
          script: |
            const deployment = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.pull_request.head.sha,
              environment: 'production',
              description: `Deploy PR #${context.payload.pull_request.number} to production`,
              auto_merge: false,
              required_contexts: [],
              production_environment: true
            });
            return deployment.data.id;
          result-encoding: string
      
      - name: Deploy to Cloudflare Workers (Production)
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: cloudflare/workers
          command: deploy
          wranglerVersion: '4.24.3'
      
      - name: Update deployment status - Success
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: ${{ steps.deployment.outputs.result }},
              state: 'success',
              environment_url: 'https://list-cutter.com',
              description: 'Deployment to production succeeded'
            });
      
      - name: Update deployment status - Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: ${{ steps.deployment.outputs.result }},
              state: 'failure',
              description: 'Deployment to production failed'
            });
      
      - name: Comment on PR - Success
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `🚀 **Deployment to PRODUCTION successful!**
            
            🌐 **Production URL**: https://list-cutter.com
            📝 **Commit**: \`${context.payload.pull_request.head.sha.substring(0, 7)}\`
            🏷️ **Triggered by**: \`deploy-prod\` label
            ⚠️ **Environment**: PRODUCTION
            
            The changes in this PR are now LIVE in production.`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: comment
            });
      
      - name: Comment on PR - Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `❌ **Deployment to PRODUCTION failed**
            
            📝 **Commit**: \`${context.payload.pull_request.head.sha.substring(0, 7)}\`
            🏷️ **Triggered by**: \`deploy-prod\` label
            ⚠️ **Environment**: PRODUCTION
            
            Please check the [workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details.
            
            **Note**: Production deployment was blocked. Please fix the issues and try again.`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: comment
            });