name: Puppeteer E2E Tests

on:
  push:
    branches: [main, feature-cut-mvp]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Puppeteer tests
        run: npm run test:puppeteer
        env:
          CI: true
      
      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: error-screenshots
          path: ./debug-*.png
          retention-days: 7