name: Puppeteer E2E Tests

on:
  push:
    branches: [main, feature-cut-mvp]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Chrome and system dependencies for Puppeteer
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3-dev \
            libatk-bridge2.0-dev \
            libdrm-dev \
            libgtk-3-dev \
            libgbm-dev
          # Install Chrome
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      
      - name: Run Puppeteer tests
        run: npm run test:puppeteer
        env:
          CI: true
      
      - name: Upload debugging artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: puppeteer-debug-artifacts
          path: |
            ./debug-*.png
            ./screenshots/
          retention-days: 7
          if-no-files-found: ignore